{ ... }:
{
  home.file.".hammerspoon/init.lua".text = ''
    -- Hammerspoon config: window snapping, app launching, window picker
    -- Workspace switching is handled by AeroSpace (alt+h/l, alt+shift+h/l).
    -- Generated by nix-darwin home-manager

    -- Reload config automatically on change
    local configWatcher = hs.pathwatcher.new(os.getenv("HOME") .. "/.hammerspoon/", function(files)
      local doReload = false
      for _, file in pairs(files) do
        if file:sub(-4) == ".lua" then doReload = true end
      end
      if doReload then hs.reload() end
    end)
    configWatcher:start()

    ---------------------------------------------------------------------------
    -- Window snapping (alt+arrows)
    ---------------------------------------------------------------------------

    hs.window.animationDuration = 0

    local gap = 8

    local function snapWindow(position)
      local win = hs.window.focusedWindow()
      if not win then return end
      local screen = win:screen():frame()

      if position == "left" then
        win:setFrame(hs.geometry.rect(screen.x, screen.y, screen.w / 2 - gap / 2, screen.h))
      elseif position == "right" then
        win:setFrame(hs.geometry.rect(screen.x + screen.w / 2 + gap / 2, screen.y, screen.w / 2 - gap / 2, screen.h))
      elseif position == "maximize" then
        win:setFrame(screen)
      elseif position == "center" then
        local w = screen.w * 0.7
        local h = screen.h * 0.8
        win:setFrame(hs.geometry.rect(
          screen.x + (screen.w - w) / 2,
          screen.y + (screen.h - h) / 2,
          w, h
        ))
      end
    end

    hs.hotkey.bind({"alt"}, "left",  function() snapWindow("left") end)
    hs.hotkey.bind({"alt"}, "right", function() snapWindow("right") end)
    hs.hotkey.bind({"alt"}, "up",    function() snapWindow("maximize") end)
    hs.hotkey.bind({"alt"}, "down",  function() snapWindow("center") end)

    ---------------------------------------------------------------------------
    -- App launching
    ---------------------------------------------------------------------------

    hs.hotkey.bind({"alt"}, "return", function()
      hs.application.launchOrFocus("Ghostty")
    end)

    hs.hotkey.bind({"alt", "shift"}, "return", function()
      hs.application.launchOrFocus("Google Chrome")
    end)

    ---------------------------------------------------------------------------
    -- Window picker: alt+tab shows letter hints for all windows on this space
    ---------------------------------------------------------------------------
    hs.hotkey.bind({"alt"}, "tab", function()
      local filter = hs.window.filter.new():setCurrentSpace(true)
      hs.hints.windowHints(filter:getWindows())
    end)
  '';
}
