{ ... }:
{
  home.file.".hammerspoon/init.lua".text = ''
    -- Hammerspoon config: workspace navigation, window snapping, app launching
    -- Generated by nix-darwin home-manager

    -- Reload config automatically on change
    local configWatcher = hs.pathwatcher.new(os.getenv("HOME") .. "/.hammerspoon/", function(files)
      local doReload = false
      for _, file in pairs(files) do
        if file:sub(-4) == ".lua" then doReload = true end
      end
      if doReload then hs.reload() end
    end)
    configWatcher:start()

    local spaces = require("hs.spaces")

    ---------------------------------------------------------------------------
    -- Helpers
    ---------------------------------------------------------------------------

    -- Get ordered user spaces for the screen the focused window is on
    local function getUserSpaces()
      local win = hs.window.focusedWindow()
      if not win then return nil, nil, nil end
      local screen = win:screen()
      local uuid = screen:getUUID()
      local allSpaces = spaces.allSpaces()
      local screenSpaces = allSpaces[uuid]
      if not screenSpaces then return nil, nil, nil end

      -- Filter to user spaces only (exclude fullscreen spaces)
      local userSpaces = {}
      for _, spc in ipairs(screenSpaces) do
        if spaces.spaceType(spc) == "user" then
          table.insert(userSpaces, spc)
        end
      end

      -- Find current space index
      local winSpaces = spaces.windowSpaces(win)
      if not winSpaces or #winSpaces == 0 then return userSpaces, nil, win end
      local currentSpaceID = winSpaces[1]
      for i, spc in ipairs(userSpaces) do
        if spc == currentSpaceID then
          return userSpaces, i, win
        end
      end
      return userSpaces, nil, win
    end

    ---------------------------------------------------------------------------
    -- Space switching via ctrl+arrow (native Mission Control shortcut)
    ---------------------------------------------------------------------------

    local function switchSpace(dir)
      hs.eventtap.keyStroke({"ctrl"}, dir, 0)
    end

    -- alt+h: space left
    hs.hotkey.bind({"alt"}, "h", function() switchSpace("left") end)
    -- alt+l: space right
    hs.hotkey.bind({"alt"}, "l", function() switchSpace("right") end)

    ---------------------------------------------------------------------------
    -- Move window to adjacent space (click-drag + ctrl+arrow approach)
    -- Works on macOS Sequoia where hs.spaces.moveWindowToSpace is broken
    ---------------------------------------------------------------------------

    local function moveWindowOneSpace(dir)
      local win = hs.window.focusedWindow()
      if not win or not win:isStandard() then return end
      if win:isFullScreen() then return end

      local screen = win:screen()
      local uuid = screen:getUUID()
      local allSp = spaces.allSpaces()
      local screenSpaces = allSp[uuid]
      if not screenSpaces then return end

      -- Filter to user spaces
      local userSpaces = {}
      for _, spc in ipairs(screenSpaces) do
        if spaces.spaceType(spc) == "user" then
          table.insert(userSpaces, spc)
        end
      end

      local winSpaces = spaces.windowSpaces(win)
      if not winSpaces or #winSpaces == 0 then return end
      local initialSpace = winSpaces[1]

      -- Check if we're at the edge
      local atEdge = false
      if dir == "right" and initialSpace == userSpaces[#userSpaces] then atEdge = true end
      if dir == "left" and initialSpace == userSpaces[1] then atEdge = true end
      if atEdge then return end

      -- Simulate click on window's zoom button area, then ctrl+arrow to drag it
      local currentCursor = hs.mouse.getRelativePosition()
      local zoomRect = win:zoomButtonRect()
      if not zoomRect then return end
      local safePoint = hs.geometry.point(zoomRect.x - 1, zoomRect.y - 1)

      hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseDown, safePoint):post()
      switchSpace(dir)
      hs.timer.waitUntil(
        function() return spaces.windowSpaces(win)[1] ~= initialSpace end,
        function()
          hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseUp, safePoint):post()
          hs.mouse.setRelativePosition(currentCursor)
        end,
        0.05
      )
    end

    -- alt+shift+h: move window to space left
    hs.hotkey.bind({"alt", "shift"}, "h", function() moveWindowOneSpace("left") end)
    -- alt+shift+l: move window to space right
    hs.hotkey.bind({"alt", "shift"}, "l", function() moveWindowOneSpace("right") end)

    ---------------------------------------------------------------------------
    -- Window snapping
    ---------------------------------------------------------------------------

    local function snapWindow(position)
      local win = hs.window.focusedWindow()
      if not win then return end
      local screen = win:screen():frame()

      if position == "left" then
        win:setFrame(hs.geometry.rect(screen.x, screen.y, screen.w / 2, screen.h))
      elseif position == "right" then
        win:setFrame(hs.geometry.rect(screen.x + screen.w / 2, screen.y, screen.w / 2, screen.h))
      elseif position == "maximize" then
        win:setFrame(screen)
      elseif position == "center" then
        local w = screen.w * 0.7
        local h = screen.h * 0.8
        win:setFrame(hs.geometry.rect(
          screen.x + (screen.w - w) / 2,
          screen.y + (screen.h - h) / 2,
          w, h
        ))
      end
    end

    -- alt+arrow keys for snapping
    hs.hotkey.bind({"alt"}, "left",  function() snapWindow("left") end)
    hs.hotkey.bind({"alt"}, "right", function() snapWindow("right") end)
    hs.hotkey.bind({"alt"}, "up",    function() snapWindow("maximize") end)
    hs.hotkey.bind({"alt"}, "down",  function() snapWindow("center") end)

    ---------------------------------------------------------------------------
    -- App launching
    ---------------------------------------------------------------------------

    -- alt+return: Ghostty
    hs.hotkey.bind({"alt"}, "return", function()
      hs.execute("open -na Ghostty")
    end)

    -- alt+shift+return: Chrome
    hs.hotkey.bind({"alt", "shift"}, "return", function()
      hs.application.launchOrFocus("Google Chrome")
    end)

    ---------------------------------------------------------------------------
    -- Disable window animation for snappy feel
    ---------------------------------------------------------------------------
    hs.window.animationDuration = 0
  '';
}
