{ ... }:
{
  home.file.".hammerspoon/init.lua".text = ''
    -- Hammerspoon config: workspace navigation, window snapping, app launching
    -- Generated by nix-darwin home-manager

    -- Reload config automatically on change
    local configWatcher = hs.pathwatcher.new(os.getenv("HOME") .. "/.hammerspoon/", function(files)
      local doReload = false
      for _, file in pairs(files) do
        if file:sub(-4) == ".lua" then doReload = true end
      end
      if doReload then hs.reload() end
    end)
    configWatcher:start()

    local spaces = require("hs.spaces")

    ---------------------------------------------------------------------------
    -- Helpers
    ---------------------------------------------------------------------------

    -- Get all ordered spaces for the screen containing the focused space
    local function getNavigableSpaces()
      local currentSpace = spaces.focusedSpace()
      if not currentSpace then return nil, nil end

      local allSpaces = spaces.allSpaces()
      for _, screenSpaces in pairs(allSpaces) do
        for i, spc in ipairs(screenSpaces) do
          if spc == currentSpace then
            return screenSpaces, i
          end
        end
      end
      return nil, nil
    end

    -- After gotoSpace the space animation plays but no window gets focus
    -- automatically. Focus the frontmost window once the animation settles.
    local function focusAfterSwitch()
      hs.timer.doAfter(0.35, function()
        local win = hs.window.frontmostWindow()
        if win then win:focus() end
      end)
    end

    ---------------------------------------------------------------------------
    -- Space switching
    -- Debounced so rapid keypresses don't queue up animations.
    ---------------------------------------------------------------------------

    local switching = false

    local function switchSpace(dir)
      if switching then return end
      local navSpaces, idx = getNavigableSpaces()
      if not navSpaces or not idx then return end
      local target
      if dir == "left" and idx > 1 then
        target = navSpaces[idx - 1]
      elseif dir == "right" and idx < #navSpaces then
        target = navSpaces[idx + 1]
      end
      if target then
        switching = true
        spaces.gotoSpace(target)
        focusAfterSwitch()
        hs.timer.doAfter(0.5, function() switching = false end)
      end
    end

    -- alt+h: space left
    hs.hotkey.bind({"alt"}, "h", function() switchSpace("left") end)
    -- alt+l: space right
    hs.hotkey.bind({"alt"}, "l", function() switchSpace("right") end)

    ---------------------------------------------------------------------------
    -- Move window to adjacent space
    -- Uses hs.spaces.moveWindowToSpace (works on Sequoia with window ID).
    -- Follows the window to its new space and re-focuses it.
    ---------------------------------------------------------------------------

    local function moveWindowOneSpace(dir)
      local win = hs.window.focusedWindow()
      if not win or not win:isStandard() then return end
      if win:isFullScreen() then return end

      local navSpaces, idx = getNavigableSpaces()
      if not navSpaces or not idx then return end

      local target
      if dir == "left" and idx > 1 then
        target = navSpaces[idx - 1]
      elseif dir == "right" and idx < #navSpaces then
        target = navSpaces[idx + 1]
      end
      if not target then return end

      spaces.moveWindowToSpace(win:id(), target)
      spaces.gotoSpace(target)
      hs.timer.doAfter(0.35, function() win:focus() end)
    end

    -- alt+shift+h: move window to space left
    hs.hotkey.bind({"alt", "shift"}, "h", function() moveWindowOneSpace("left") end)
    -- alt+shift+l: move window to space right
    hs.hotkey.bind({"alt", "shift"}, "l", function() moveWindowOneSpace("right") end)

    ---------------------------------------------------------------------------
    -- Window snapping
    ---------------------------------------------------------------------------

    local gap = 8 -- pixels between side-by-side snapped windows

    local function snapWindow(position)
      local win = hs.window.focusedWindow()
      if not win then return end
      local screen = win:screen():frame()

      if position == "left" then
        win:setFrame(hs.geometry.rect(screen.x, screen.y, screen.w / 2 - gap / 2, screen.h))
      elseif position == "right" then
        win:setFrame(hs.geometry.rect(screen.x + screen.w / 2 + gap / 2, screen.y, screen.w / 2 - gap / 2, screen.h))
      elseif position == "maximize" then
        win:setFrame(screen)
      elseif position == "center" then
        local w = screen.w * 0.7
        local h = screen.h * 0.8
        win:setFrame(hs.geometry.rect(
          screen.x + (screen.w - w) / 2,
          screen.y + (screen.h - h) / 2,
          w, h
        ))
      end
    end

    -- alt+arrow keys for snapping
    hs.hotkey.bind({"alt"}, "left",  function() snapWindow("left") end)
    hs.hotkey.bind({"alt"}, "right", function() snapWindow("right") end)
    hs.hotkey.bind({"alt"}, "up",    function() snapWindow("maximize") end)
    hs.hotkey.bind({"alt"}, "down",  function() snapWindow("center") end)

    ---------------------------------------------------------------------------
    -- App launching
    ---------------------------------------------------------------------------

    -- alt+return: Ghostty
    hs.hotkey.bind({"alt"}, "return", function()
      hs.application.launchOrFocus("Ghostty")
    end)

    -- alt+shift+return: Chrome
    hs.hotkey.bind({"alt", "shift"}, "return", function()
      hs.application.launchOrFocus("Google Chrome")
    end)

    ---------------------------------------------------------------------------
    -- Window picker: alt+tab shows letter hints for all windows on this space
    -- Press the highlighted letter to jump to that window.
    -- (cmd+tab is the native app switcher and is untouched)
    ---------------------------------------------------------------------------
    hs.hotkey.bind({"alt"}, "tab", function()
      local filter = hs.window.filter.new():setCurrentSpace(true)
      hs.hints.windowHints(filter:getWindows())
    end)

    ---------------------------------------------------------------------------
    -- Disable window animation for snappy feel
    ---------------------------------------------------------------------------
    hs.window.animationDuration = 0
  '';
}
