# Pre-commit hooks via git-hooks.nix
{ inputs, ... }:
{
  imports = [ inputs.git-hooks.flakeModule ];

  perSystem =
    { pkgs, ... }:
    {
      # Use prek (a fast Rust reimplementation of pre-commit) as the hook
      # runner instead of upstream `pre-commit`. It's a drop-in replacement
      # that reads the same generated config, but its closure is far lighter —
      # notably it avoids the costly Darwin build that `pre-commit` pulls in.
      pre-commit.settings.package = pkgs.prek;

      pre-commit.settings.hooks = {
        # Nix formatting
        nixfmt.enable = true;

        # Nix linting — hardware configs are generated by nixos-generate-config and don't
        # conform to the usual style rules, so exclude them from both linters.
        statix = {
          enable = true;
          settings.ignore = [ "modules/hosts/_*-hardware.nix" ];
          # statix's insta snapshot tests are broken on the pinned nixos-26.05
          # revision (the `empty_list_concat` fixtures fail in checkPhase on
          # aarch64-darwin), so skip the check phase — we only consume the
          # built binary, not its test suite. See #540. The same override is
          # applied in modules/programs/neovim.nix (extraPackages); remove both
          # together once a nixpkgs bump ships a statix whose snapshots pass.
          package = pkgs.statix.overrideAttrs (_: {
            doCheck = false;
          });
        };
        deadnix = {
          enable = true;
          excludes = [ "modules/hosts/_.*-hardware\\.nix$" ];
        };

        # Prevent secrets from leaking
        ripsecrets.enable = true;

        # YAML/JSON validation. Authentik blueprints use custom YAML tags
        # (`!Env`, `!Find`, `!KeyOf`) that pyyaml's safe loader rejects, so
        # exclude that directory from this hook.
        check-yaml = {
          enable = true;
          excludes = [ "^modules/(apps|system)/[^/]*-blueprints[^/]*/" ];
        };
        check-json.enable = true;

        # Whitespace hygiene
        trim-trailing-whitespace.enable = true;
        end-of-file-fixer.enable = true;
      };
    };
}
