# Pre-commit hooks via git-hooks.nix
{ inputs, ... }:
{
  imports = [ inputs.git-hooks.flakeModule ];

  perSystem = _: {
    pre-commit.settings.hooks = {
      # Nix formatting
      nixfmt-rfc-style.enable = true;

      # Nix linting — hardware configs are generated by nixos-generate-config and don't
      # conform to the usual style rules, so exclude them from both linters.
      statix = {
        enable = true;
        settings.ignore = [ "modules/hosts/_*-hardware.nix" ];
      };
      deadnix = {
        enable = true;
        excludes = [ "modules/hosts/_.*-hardware\\.nix$" ];
      };

      # Prevent secrets from leaking
      ripsecrets.enable = true;

      # YAML/JSON validation
      check-yaml.enable = true;
      check-json.enable = true;

      # Whitespace hygiene
      trim-trailing-whitespace.enable = true;
      end-of-file-fixer.enable = true;
    };
  };
}
