import json
import os
import sys
import tempfile
import urllib.parse
import urllib.request

OUT = os.environ["TEXTFILE_OUT"]
ENDPOINTS = json.load(open(os.environ["ENDPOINTS_FILE"]))
API_KEY_FILE = os.environ["API_KEY_FILE"]

# Long enough to ride out a busy child answering a metrics
# task behind a decode, short enough that a powered-off
# terra doesn't stall a 1-minute timer.
TIMEOUT = 10

# The four states llama.cpp's router reports
# (server_model_status_to_string). Emitted as a state set,
# the way node_exporter does node_systemd_unit_state, so a
# transition is visible as a series flipping rather than a
# label value changing. Anything unrecognised leaves all
# four at 0.
STATES = ["unloaded", "loading", "loaded", "sleeping"]

# llama.cpp names its metrics "llamacpp:foo", and a colon in
# a metric name is reserved for recording rules — PromQL can
# only reach it through a __name__ matcher, which Grafana
# panels handle badly. Renamed on the way through, and given
# the model/alias labels the source has no room for.
COUNTERS = {
    "llamacpp:prompt_tokens_total": (
        "llama_prompt_tokens_total",
        "Prompt tokens processed by this model since its child process started.",
    ),
    "llamacpp:prompt_seconds_total": (
        "llama_prompt_seconds_total",
        "Seconds spent processing prompts since this model's child process started.",
    ),
    "llamacpp:tokens_predicted_total": (
        "llama_tokens_predicted_total",
        "Tokens generated by this model since its child process started.",
    ),
    "llamacpp:tokens_predicted_seconds_total": (
        "llama_tokens_predicted_seconds_total",
        "Seconds spent generating tokens since this model's child process started.",
    ),
    "llamacpp:n_decode_total": (
        "llama_decode_total",
        "llama_decode() calls since this model's child process started.",
    ),
}
GAUGES = {
    "llamacpp:n_tokens_max": (
        "llama_tokens_max",
        "Largest prompt+generation token count this model has been asked for, against its configured ctxSize.",
    ),
    "llamacpp:requests_processing": (
        "llama_requests_processing",
        "Requests this model is currently serving.",
    ),
}


def read_api_key():
    # Missing key is survivable: /v1/models is public, so
    # state still publishes and only the token counters go
    # dark (recorded as llama_model_metrics_error).
    try:
        with open(API_KEY_FILE) as fh:
            return fh.read().strip()
    except OSError as exc:
        sys.stderr.write("api key unreadable: %s\n" % exc)
        return None


def fetch(url, api_key=None):
    req = urllib.request.Request(url)
    if api_key:
        req.add_header("Authorization", "Bearer " + api_key)
    with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
        return resp.read().decode()


def parse_prometheus(text):
    out = {}
    for line in text.splitlines():
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) == 2:
            try:
                out[parts[0]] = float(parts[1])
            except ValueError:
                pass
    return out


def labels(**kwargs):
    def esc(v):
        return v.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")

    body = ",".join('%s="%s"' % (k, esc(v)) for k, v in sorted(kwargs.items()))
    return "{" + body + "}"


rows = {}


def emit(metric, mtype, help_text, label_str, value):
    rows.setdefault(metric, (mtype, help_text, []))[2].append((label_str, value))


api_key = read_api_key()

for server in sorted(ENDPOINTS):
    base = ENDPOINTS[server].rstrip("/")
    try:
        models = json.loads(fetch(base + "/v1/models"))["data"]
    except Exception as exc:
        # A powered-off terra lands here every minute. It is
        # a value, not a fault: publish up=0 and move on.
        sys.stderr.write("%s: /v1/models failed: %s\n" % (server, exc))
        emit("llama_server_up", "gauge", "Whether this llama-server router answered /v1/models.", labels(llama_server=server), 0)
        continue
    emit("llama_server_up", "gauge", "Whether this llama-server router answered /v1/models.", labels(llama_server=server), 1)

    for model in models:
        name = model["id"]
        # Joined rather than one series per alias: the label
        # is here so a dashboard can legend by role name
        # ("text", "vision", "code") instead of by GGUF, and
        # every model in this fleet has exactly one.
        alias = ",".join(sorted(model.get("aliases") or []))
        state = model.get("status", {}).get("value", "")
        common = dict(llama_server=server, model=name, alias=alias)

        for candidate in STATES:
            emit(
                "llama_model_state",
                "gauge",
                "Router-reported state of this model, one series per state (loaded means resident and awake; sleeping means the child is alive but has handed its VRAM back).",
                labels(state=candidate, **common),
                int(candidate == state),
            )

        # Only an awake model may be asked for /metrics —
        # see the module header. `autoload=false` is the
        # second line of defence for the case where the
        # model sleeps between this check and the request.
        if state != "loaded":
            continue

        url = "%s/metrics?model=%s&autoload=false" % (
            base,
            urllib.parse.quote(name, safe=""),
        )
        try:
            parsed = parse_prometheus(fetch(url, api_key))
            failed = 0
        except Exception as exc:
            sys.stderr.write("%s: /metrics for %s failed: %s\n" % (server, name, exc))
            parsed = {}
            failed = 1

        # The one silent-failure mode worth a series of its
        # own: this exporter depends on `--metrics` reaching
        # the child through llama.cpp's argv merge, and if
        # that ever stops happening the counters just go
        # quiet while everything else looks healthy.
        emit(
            "llama_model_metrics_error",
            "gauge",
            "Whether the last /metrics read for this loaded model failed.",
            labels(**common),
            failed,
        )

        for src, (dst, help_text) in COUNTERS.items():
            if src in parsed:
                emit(dst, "counter", help_text + " Resets when the model is evicted; survives sleep/wake.", labels(**common), parsed[src])
        for src, (dst, help_text) in GAUGES.items():
            if src in parsed:
                emit(dst, "gauge", help_text, labels(**common), parsed[src])

# Atomic write via tempfile + rename, so node_exporter never
# reads a half-written file.
fd, tmp = tempfile.mkstemp(dir=os.path.dirname(OUT), prefix=".llama.prom.")
with os.fdopen(fd, "w") as fh:
    for metric in sorted(rows):
        mtype, help_text, samples = rows[metric]
        fh.write("# HELP %s %s\n" % (metric, help_text))
        fh.write("# TYPE %s %s\n" % (metric, mtype))
        for label_str, value in samples:
            fh.write("%s%s %s\n" % (metric, label_str, repr(float(value))))
os.chmod(tmp, 0o644)
os.rename(tmp, OUT)
